(source melpa)
(source gnu)

(depends-on "pallet")

(depends-on "ag")
(depends-on "auto-complete")
(depends-on "better-defaults")
(depends-on "cider")
(depends-on "clojure-mode")
(depends-on "dired-details+")
(depends-on "docker")
(depends-on "evil")
(depends-on "evil-leader")
(depends-on "evil-nerd-commenter")
(depends-on "flx-ido")
(depends-on "idomenu")
(depends-on "ido-select-window")
(depends-on "ido-ubiquitous")
(depends-on "ido-vertical-mode")
(depends-on "paredit")
(depends-on "projectile")
(depends-on "ujelly-theme")
