alias e   "nvim"
alias vi  "nvim"
alias vim "nvim"

alias git  "hub"
alias gti  "git"
alias gci  "git commit -m"
alias gco  "git checkout"
alias gl   "git pull"
alias gp   "git push"
alias gpo  "git push -u origin (git rev-parse --abbrev-ref HEAD)"
alias gr   "git pull-request"
alias gst  "git status"
alias glog "git log --pretty=format:'%C(auto)%h - %<(80,trunc)%s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
